library(tidyverse)

# Conferences for each Sport

conference <- data_frame(
  Numeric_Code = c(
    # Football
    372, 176, 204, 316, 369, 102, 104, 105, 106, 107, 108, 138, 165,
    140, 355, 304, 167, 110, 168, 139, 111, 112, 113, 170, 151, 366,
    172, 333, 173, 352, 302, 367, 144, 371, 145, 174, 213, 311, 146,
    320, 175, 322, 327, 335, 117, 309, 147, 179, 180, 148, 119, 121,
    315, 356, 181, 182, 183, 123, 370, 203, 184, 185, 186, 187, 189,
    373, 153, 125, 359, 155, 205, 191, 126, 192, 127, 128, 158, 129,
    194, 159, 340, 160, 130, 368, 197, 198, 131, 161, 132, 133, 134,
    171, 200, 354, 201, 163, 137, 202, 342, -1, -2,
    # Basketball
    214, 101, 372, 376, 319, 176, 204, 316, 369, 103, 102, 375, 135,
    104, 105, 106, 107, 108, 109, 138, 301, 164, 328, 165, 323, 140,
    304, 166, 167, 110, 364, 168, 207, 139, 111, 305, 141, 170, 151,
    115, 172, 333, 208, 352, 302, 367, 144, 371, 145, 174, 213, 311,
    337, 146, 320, 175, 209, 122, 318, 322, 327, 335, 117, 309, 361,
    178, 147, 179, 118, 180, 148, 119, 121, 315, 181, 182, 183, 123,
    370, 203, 363, 185, 186, 187, 215, 189, 365, 373, 153, 125, 359,
    155, 205, 191, 126, 192, 156, 127, 128, 157, 158, 194, 353, 374,
    159, 196, 340, 160, 130, 368, 197, 198, 131, 161, 334, 132, 133,
    195, 199, 134, 162, 120, 171, 200, 354, 201, 136, 163, 137, 202,
    307, 342, -1, -2,
    # Baseball
    214, 101, 372, 319, 176, 204, 316, 369, 103, 102, 375, 135, 104,
    105, 106, 107, 108, 109, 138, 301, 164, 328, 165, 323, 140, 304,
    166, 167, 110, 364, 168, 207, 139, 111, 305, 170, 151, 115, 332,
    172, 333, 208, 302, 367, 144, 371, 145, 174, 213, 311, 337, 146,
    320, 175, 209, 122, 318, 322, 335, 117, 309, 361, 178, 147, 179,
    118, 180, 148, 119, 121, 315, 181, 182, 183, 123, 370, 203, 363,
    185, 186, 187, 215, 189, 365, 373, 153, 125, 359, 155, 205, 191,
    126, 192, 156, 127, 128, 157, 158, 194, 353, 374, 159, 196, 340,
    160, 130, 368, 197, 198, 131, 161, 334, 132, 133, 195, 199, 134,
    162, 120, 171, 200, 354, 201, 136, 163, 137, 202, 307, 342, -1, -2,
    # Track
    214, 101, 372, 376, 319, 176, 204, 316, 369, 103, 102, 375, 135,
    104, 105, 106, 107, 108, 109, 138, 301, 164, 328, 165, 323, 140,
    304, 166, 167, 110, 364, 168, 207, 139, 111, 305, 112, 141, 170,
    151, 115, 172, 333, 208, 352, 302, 367, 144, 145, 371, 174, 213,
    311, 337, 146, 320, 175, 122, 318, 322, 335, 117, 309, 361, 178,
    147, 179, 118, 180, 148, 119, 121, 315, 181, 182, 183, 123, 370,
    124, 203, 363, 185, 186, 187, 215, 189, 365, 373, 153, 125, 359,
    155, 205, 191, 126, 192, 156, 127, 128, 157, 158, 194, 353, 374,
    159, 196, 340, 160, 130, 368, 197, 198, 131, 161, 334, 132, 133,
    195, 199, 134, 162, 120, 171, 200, 354, 201, 136, 163, 137, 202,
    307, 342, -1, -2
  ),
  Conference = c(
    # Football
    "American Athletic Conference",
    "American Rivers Conference",
    "American Southwest Conference",
    "Appalachian Athletic Conference",
    "Association of Independent Institutions",
    "Atlantic Coast Conference",
    "Big East Conference",
    "Big Sky Conference",
    "Big South Conference",
    "Big Ten Conference",
    "Big Twelve Conference",
    "California Collegiate Athletic Association",
    "Centennial Conference",
    "Central Intercollegiate Athletic Association",
    "Central States Football League",
    "Chicagoland Collegiate Athletic Conference",
    "College Conference of Illinois and Wisconsin",
    "Colonial Athletic Association",
    "Commonwealth Coast Conference",
    "Conference Carolinas",
    "Conference USA",
    "Division I Independents",
    "Division I-A Independents",
    "Division III Independents",
    "East Coast Conference",
    "Eastern Collegiate Football Conference",
    "Empire Eight",
    "The Sun Conference",
    "Freedom Football Conference",
    "Frontier Conference",
    "Golden State Athletic Conference",
    "Great American Conference",
    "Great Lakes Intercollegiate Athletic Conference",
    "Great Midwest Athletic Conference",
    "Great Lakes Valley Conference",
    "Great Northeast Athletic Conference",
    "Great Northwest Athletic Conference",
    "Great Plains Athletic Conference",
    "Gulf South Conference",
    "Heart of America Athletic Conference",
    "Heartland Collegiate Athletic Conference",
    "Independent Midwest Region",
    "Independent Northeast Region",
    "Independent Southeast Region",
    "Ivy Group",
    "Kansas Collegiate Athletic Conference",
    "Lone Star Conference",
    "Massachusetts State College Athletic Association",
    "Michigan Intercollegiate Athletic Association",
    "Mid-America Intercollegiate Athletic Association",
    "Mid-American Conference",
    "Mid-Eastern Athletic Conference",
    "Mid-South Conference",
    "Mid-States Football Association",
    "Middle Atlantic States Athletic Corporation",
    "Midwest Conference",
    "Minnesota Intercollegiate Athletic Conference",
    "Missouri Valley Conference",
    "Mountain East Conference",
    "Mountain West Conference",
    "New England Football Conference",
    "New England Small College Athletic Conference",
    "New England Women's & Men's Athletic Conference",
    "New Jersey Athletic Conference",
    "North Coast Athletic Conference",
    "North Star Athletic Association",
    "Northeast 10 Conference",
    "Northeast Conference",
    "Northern Athletics Collegiate Conference",
    "Northern Sun Intercollegiate Conference",
    "Northwest Conference",
    "Ohio Athletic Conference",
    "Ohio Valley Conference",
    "Old Dominion Athletic Conference",
    "Pacific-12 Conference",
    "Patriot League",
    "Pennsylvania State Athletic Conference",
    "Pioneer Football League",
    "Presidents' Athletic Conference",
    "Rocky Mountain Athletic Conference",
    "Sooner Athletic Conference",
    "South Atlantic Conference",
    "Southeastern Conference",
    "Southern Athletic Association",
    "Southern California Intercollegiate Athletic Conference",
    "Southern Collegiate Athletic Conference",
    "Southern Conference",
    "Southern Intercollegiate Athletic Conference",
    "Southland Conference",
    "Southwestern Athletic Conference",
    "Sun Belt Conference",
    "USA South Athletic Conference",
    "University Athletic Association",
    "Upper Midwest Athletic Conference",
    "Upstate Collegiate Athletic Association",
    "West Virginia Intercollegiate Athletic Conference",
    "Western Athletic Conference",
    "Wisconsin Intercollegiate Athletic Conference",
    "Other",
    "Not reported",
    "Not applicable",
    # Basketball
    "Allegheny Mountain Collegiate Conference",
    "America East",
    "American Athletic Conference",
    "American Collegiate Athletic Association",
    "American Midwest Conference",
    "American Rivers Conference",
    "American Southwest Conference",
    "Appalachian Athletic Conference",
    "Association of Independent Institutions",
    "Atlantic 10 Conference",
    "Atlantic Coast Conference",
    "Atlantic East Conference",
    "Atlantic Sun Conference",
    "Big East Conference",
    "Big Sky Conference",
    "Big South Conference",
    "Big Ten Conference",
    "Big Twelve Conference",
    "Big West Conference",
    "California Collegiate Athletic Association",
    "California Pacific Conference",
    "Capital Athletic Conference",
    "Cascade Collegiate Conference",
    "Centennial Conference",
    "Central Atlantic Collegiate Conference",
    "Central Intercollegiate Athletic Association",
    "Chicagoland Collegiate Athletic Conference",
    "City University of New York Athletic Conference",
    "College Conference of Illinois and Wisconsin",
    "Colonial Athletic Association",
    "Colonial States Athletic Conference",
    "Commonwealth Coast Conference",
    "Commonwealth Conference",
    "Conference Carolinas",
    "Conference USA",
    "Crossroads League",
    "Division II Independents",
    "Division III Independents",
    "East Coast Conference",
    "Eastern College Athletic Conference",
    "Empire Eight",
    "The Sun Conference",
    "Freedom Conference",
    "Frontier Conference",
    "Golden State Athletic Conference",
    "Great American Conference",
    "Great Lakes Intercollegiate Athletic Conference",
    "Great Midwest Athletic Conference",
    "Great Lakes Valley Conference",
    "Great Northeast Athletic Conference",
    "Great Northwest Athletic Conference",
    "Great Plains Athletic Conference",
    "Gulf Coast Athletic Conference",
    "Gulf South Conference",
    "Heart of America Athletic Conference",
    "Heartland Collegiate Athletic Conference",
    "Heartland Conference",
    "Horizon League",
    "Independent Mid-South Region",
    "Independent Midwest Region",
    "Independent Northeast Region",
    "Independent Southeast Region",
    "Ivy Group",
    "Kansas Collegiate Athletic Conference",
    "Landmark Conference",
    "Little East Conference",
    "Lone Star Conference",
    "Massachusetts State College Athletic Association",
    "Metro Atlantic Athletic Conference",
    "Michigan Intercollegiate Athletic Association",
    "Mid-America Intercollegiate Athletic Association",
    "Mid-American Conference",
    "Mid-Eastern Athletic Conference",
    "Mid-South Conference",
    "Middle Atlantic States Athletic Corporation",
    "Midwest Conference",
    "Minnesota Intercollegiate Athletic Conference",
    "Missouri Valley Conference",
    "Mountain East Conference",
    "Mountain West Conference",
    "New England Collegiate Conference",
    "New England Small College Athletic Conference",
    "New England Women's & Men's Athletic Conference",
    "New Jersey Athletic Conference",
    "North Atlantic Conference",
    "North Coast Athletic Conference",
    "North Eastern Athletic Conference",
    "North Star Athletic Association",
    "Northeast 10 Conference",
    "Northeast Conference",
    "Northern Athletics Collegiate Conference",
    "Northern Sun Intercollegiate Conference",
    "Northwest Conference",
    "Ohio Athletic Conference",
    "Ohio Valley Conference",
    "Old Dominion Athletic Conference",
    "Pacific West Conference",
    "Pacific-12 Conference",
    "Patriot League",
    "Peach Belt Conference",
    "Pennsylvania State Athletic Conference",
    "Presidents' Athletic Conference",
    "Red River Athletic Conference",
    "River States",
    "Rocky Mountain Athletic Conference",
    "Skyline Conference",
    "Sooner Athletic Conference",
    "South Atlantic Conference",
    "Southeastern Conference",
    "Southern Athletic Association",
    "Southern California Intercollegiate Athletic Conference",
    "Southern Collegiate Athletic Conference",
    "Southern Conference",
    "Southern Intercollegiate Athletic Conference",
    "Southern States Athletic Conference",
    "Southland Conference",
    "Southwestern Athletic Conference",
    "St. Louis Intercollegiate Athletic Conference",
    "State University of New York Athletic Conference",
    "Sun Belt Conference",
    "Sunshine State Conference",
    "The Summit League",
    "USA South Athletic Conference",
    "University Athletic Association",
    "Upper Midwest Athletic Conference",
    "Upstate Collegiate Athletic Association",
    "West Coast Conference",
    "West Virginia Intercollegiate Athletic Conference",
    "Western Athletic Conference",
    "Wisconsin Intercollegiate Ath Conference",
    "Wolverine-Hoosier Athletic Conference",
    "Other",
    "Not reported",
    "Not applicable",
    # Baseball
    "Allegheny Mountain Collegiate Conference",
    "America East",
    "American Athletic Conference",
    "American Midwest Conference",
    "American Rivers Conference",
    "American Southwest Conference",
    "Appalachian Athletic Conference",
    "Association of Independent Institutions",
    "Atlantic 10 Conference",
    "Atlantic Coast Conference",
    "Atlantic East Conference",
    "Atlantic Sun Conference",
    "Big East Conference",
    "Big Sky Conference",
    "Big South Conference",
    "Big Ten Conference",
    "Big Twelve Conference",
    "Big West Conference",
    "California Collegiate Athletic Association",
    "California Pacific Conference",
    "Capital Athletic Conference",
    "Cascade Collegiate Conference",
    "Centennial Conference",
    "Central Atlantic Collegiate Conference",
    "Central Intercollegiate Athletic Association",
    "Chicagoland Collegiate Athletic Conference",
    "City University of New York Athletic Conference",
    "College Conference of Illinois and Wisconsin",
    "Colonial Athletic Association",
    "Colonial States Athletic Conference",
    "Commonwealth Coast Conference",
    "Commonwealth Conference",
    "Conference Carolinas",
    "Conference USA",
    "Crossroads League",
    "Division III Independents",
    "East Coast Conference",
    "Eastern College Athletic Conference",
    "Eastern Intercollegiate Athletic Conference",
    "Empire Eight",
    "The Sun Conference",
    "Freedom Conference",
    "Golden State Athletic Conference",
    "Great American Conference",
    "Great Lakes Intercollegiate Athletic Conference",
    "Great Midwest Athletic Conference",
    "Great Lakes Valley Conference",
    "Great Northeast Athletic Conference",
    "Great Northwest Athletic Conference",
    "Great Plains Athletic Conference",
    "Gulf Coast Athletic Conference",
    "Gulf South Conference",
    "Heart of America Athletic Conference",
    "Heartland Collegiate Athletic Conference",
    "Heartland Conference",
    "Horizon League",
    "Independent Mid-South Region",
    "Independent Midwest Region",
    "Independent Southeast Region",
    "Ivy Group",
    "Kansas Collegiate Athletic Conference",
    "Landmark Conference",
    "Little East Conference",
    "Lone Star Conference",
    "Massachusetts State College Athletic Association",
    "Metro Atlantic Athletic Conference",
    "Michigan Intercollegiate Athletic Association",
    "Mid-America Intercollegiate Athletic Association",
    "Mid-American Conference",
    "Mid-Eastern Athletic Conference",
    "Mid-South Conference",
    "Middle Atlantic States Athletic Corporation",
    "Midwest Conference",
    "Minnesota Intercollegiate Athletic Conference",
    "Missouri Valley Conference",
    "Mountain East Conference",
    "Mountain West Conference",
    "New England Collegiate Conference",
    "New England Small College Athletic Conference",
    "New England Women's & Men's Athletic Conference",
    "New Jersey Athletic Conference",
    "North Atlantic Conference",
    "North Coast Athletic Conference",
    "North Eastern Athletic Conference",
    "North Star Athletic Association",
    "Northeast 10 Conference",
    "Northeast Conference",
    "Northern Athletics Collegiate Conference",
    "Northern Sun Intercollegiate Conference",
    "Northwest Conference",
    "Ohio Athletic Conference",
    "Ohio Valley Conference",
    "Old Dominion Athletic Conference",
    "Pacific West Conference",
    "Pacific-12 Conference",
    "Patriot League",
    "Peach Belt Conference",
    "Pennsylvania State Athletic Conference",
    "Presidents' Athletic Conference",
    "Red River Athletic Conference",
    "River States",
    "Rocky Mountain Athletic Conference",
    "Skyline Conference",
    "Sooner Athletic Conference",
    "South Atlantic Conference",
    "Southeastern Conference",
    "Southern Athletic Association",
    "Southern California Intercollegiate Athletic Conference",
    "Southern Collegiate Athletic Conference",
    "Southern Conference",
    "Southern Intercollegiate Athletic Conference",
    "Southern States Athletic Conference",
    "Southland Conference",
    "Southwestern Athletic Conference",
    "St. Louis Intercollegiate Athletic Conference",
    "State University of New York Athletic Conference",
    "Sun Belt Conference",
    "Sunshine State Conference",
    "The Summit League",
    "USA South Athletic Conference",
    "University Athletic Association",
    "Upper Midwest Athletic Conference",
    "Upstate Collegiate Athletic Association",
    "West Coast Conference",
    "West Virginia Intercollegiate Athletic Conference",
    "Western Athletic Conference",
    "Wisconsin Intercollegiate Athletic Conference",
    "Wolverine-Hoosier Athletic Conference",
    "Other",
    "Not reported",
    "Not applicable",
    # Track
    "Allegheny Mountain Collegiate Conference",
    "America East",
    "American Athletic Conference",
    "American Collegiate Athletic Association",
    "American Midwest Conference",
    "American Rivers Conference",
    "American Southwest Conference",
    "Appalachian Athletic Conference",
    "Association of Independent Institutions",
    "Atlantic 10 Conference",
    "Atlantic Coast Conference",
    "Atlantic East Conference",
    "Atlantic Sun Conference",
    "Big East Conference",
    "Big Sky Conference",
    "Big South Conference",
    "Big Ten Conference",
    "Big Twelve Conference",
    "Big West Conference",
    "California Collegiate Athletic Association",
    "California Pacific Conference",
    "Capital Athletic Conference",
    "Cascade Collegiate Conference",
    "Centennial Conference",
    "Central Atlantic Collegiate Conference",
    "Central Intercollegiate Athletic Association",
    "Chicagoland Collegiate Athletic Conference",
    "City University of New York Athletic Conference",
    "College Conference of Illinois and Wisconsin",
    "Colonial Athletic Association",
    "Colonial States Athletic Conference",
    "Commonwealth Coast Conference",
    "Commonwealth Conference",
    "Conference Carolinas",
    "Conference USA",
    "Crossroads League",
    "Division I Independents",
    "Division II Independents",
    "Division III Independents",
    "East Coast Conference",
    "Eastern College Athletic Conference",
    "Empire Eight",
    "The Sun Conference",
    "Freedom Conference",
    "Frontier Conference",
    "Golden State Athletic Conference",
    "Great American Conference",
    "Great Lakes Intercollegiate Athletic Conference",
    "Great Lakes Valley Conference",
    "Great Midwest Athletic Conference",
    "Great Northeast Athletic Conference",
    "Great Northwest Athletic Conference",
    "Great Plains Athletic Conference",
    "Gulf Coast Athletic Conference",
    "Gulf South Conference",
    "Heart of America Athletic Conference",
    "Heartland Collegiate Athletic Conference",
    "Horizon League",
    "Independent Mid-South Region",
    "Independent Midwest Region",
    "Independent Southeast Region",
    "Ivy Group",
    "Kansas Collegiate Athletic Conference",
    "Landmark Conference",
    "Little East Conference",
    "Lone Star Conference",
    "Massachusetts State College Athletic Association",
    "Metro Atlantic Athletic Conference",
    "Michigan Intercollegiate Athletic Association",
    "Mid-America Intercollegiate Athletic Association",
    "Mid-American Conference",
    "Mid-Eastern Athletic Conference",
    "Mid-South Conference",
    "Middle Atlantic States Athletic Corporation",
    "Midwest Conference",
    "Minnesota Intercollegiate Athletic Conference",
    "Missouri Valley Conference",
    "Mountain East Conference",
    "Mountain Pacific Sports Federation",
    "Mountain West Conference",
    "New England Collegiate Conference",
    "New England Small College Athletic Conference",
    "New England Women's & Men's Athletic Conference",
    "New Jersey Athletic Conference",
    "North Atlantic Conference",
    "North Coast Athletic Conference",
    "North Eastern Athletic Conference",
    "North Star Athletic Association",
    "Northeast 10 Conference",
    "Northeast Conference",
    "Northern Athletics Conference",
    "Northern Sun Intercollegiate Conference",
    "Northwest Conference",
    "Ohio Athletic Conference",
    "Ohio Valley Conference",
    "Old Dominion Athletic Conference",
    "Pacific West Conference",
    "Pacific-12 Conference",
    "Patriot League",
    "Peach Belt Conference",
    "Pennsylvania State Athletic Conference",
    "Presidents' Athletic Conference",
    "Red River Athletic Conference",
    "River States",
    "Rocky Mountain Athletic Conference",
    "Skyline Conference",
    "Sooner Athletic Conference",
    "South Atlantic Conference",
    "Southeastern Conference",
    "Southern Athletic Association",
    "Southern California Intercollegiate Athletic Conference",
    "Southern Collegiate Athletic Conference",
    "Southern Conference",
    "Southern Intercollegiate Athletic Conference",
    "Southern States Athletic Conference",
    "Southland Conference",
    "Southwestern Athletic Conference",
    "St. Louis Intercollegiate Athletic Conference",
    "State University of New York Athletic Conference",
    "Sun Belt Conference",
    "Sunshine State Conference",
    "The Summit League",
    "USA South Athletic Conference",
    "University Athletic Association",
    "Upper Midwest Athletic Conference",
    "Upstate Collegiate Athletic Association",
    "West Coast Conference",
    "West Virginia Intercollegiate Athletic Conference",
    "Western Athletic Conference",
    "Wisconsin Intercollegiate Athletic Conference",
    "Wolverine-Hoosier Athletic Conference",
    "Other",
    "Not reported",
    "Not applicable"
  ),
  Sport = c(
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football", "Football",
    "Football",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball", "Basketball",
    "Basketball", "Basketball", "Basketball", "Basketball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball", "Baseball",
    "Baseball",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track", "Track",
    "Track", "Track", "Track", "Track"
  )
)

usethis::use_data(conference, overwrite = TRUE)
