library(tidyverse)

# Religious Affiliations Categories

relig_aff <- data_frame(
  Numeric_Code = c(
    51, 24, 52, 22, 27, 54, 28, 34, 61, 48, 55,
    35, 58, 57, 59, 74, 60, 50, 102, 36, 37, 38,
    39, 64, 41, 65, 105, 91, 42, 80, 68, 67, 43,
    69, 87, 44, 78, 106, 108, 45, 100, 79, 47, 107,
    103, 66, 73, 49, 81, 30, 92, 95, 75, 94, 97, 88,
    93, 84, 76, 71, 89, 33, 99, -2
  ),
  Religious_Affiliation =
    c(
      "African Methodist Episcopal",
      "African Methodist Episcopal Zion Church",
      "American Baptist",
      "American Evangelical Lutheran Church",
      "Assemblies of God Church",
      "Baptist",
      "Brethren Church",
      "Christ and Missionary Alliance Church",
      "Christian Church (Disciples of Christ)",
      "Christian Churches and Churches of Christ",
      "Christian Methodist Episcopal",
      "Christian Reformed Church",
      "Church of Brethren",
      "Church of God",
      "Church of the Nazarene",
      "Churches of Christ",
      "Cumberland Presbyterian",
      "Episcopal Church, Reformed",
      "Evangelical Christian",
      "Evangelical Congregational Church",
      "Evangelical Covenant Church of America",
      "Evangelical Free Church of America",
      "Evangelical Lutheran Church",
      "Free Methodist",
      "Free Will Baptist Church",
      "Friends",
      "General Baptist",
      "Greek Orthodox",
      "Interdenominational",
      "Jewish",
      "Lutheran Church - Missouri Synod",
      "Lutheran Church in America",
      "Mennonite Brethren Church",
      "Mennonite Church",
      "Missionary Church Inc",
      "Moravian Church",
      "Multiple Protestant Denomination",
      "Muslim",
      "Non-Denominational",
      "North American Baptist",
      "Original Free Will Baptist",
      "Other Protestant",
      "Pentecostal Holiness Church",
      "Plymouth Brethren",
      "Presbyterian",
      "Presbyterian Church (USA)",
      "Protestant Episcopal",
      "Reformed Church in America",
      "Reformed Presbyterian Church",
      "Roman Catholic",
      "Russian Orthodox",
      "Seventh Day Adventist",
      "Southern Baptist",
      "The Church of Jesus Christ of Latter-day Saints",
      "The Presbyterian Church in America",
      "Undenominational",
      "Unitarian Universalist",
      "United Brethren Church",
      "United Church of Christ",
      "United Methodist",
      "Wesleyan",
      "Wisconsin Evangelical Lutheran Synod",
      "Other (none of the above)",
      "Not applicable"
    )
)

usethis::use_data(relig_aff, overwrite = TRUE)
