
library(tidyverse)

# Staff Categories

staff_cat <- data_frame(Numeric_Code = c(1, 100, 101, 102, 103, 104, 105, 106, 200, 201, 202, 203, 204, 205, 206, 300,
                                         301, 302, 303, 304, 305, 306, 400, 401, 402, 403, 404, 405, 406, 410, 411, 412,
                                         413, 414, 415, 416, 420, 421, 422, 423, 424, 425, 426, 430, 431, 432, 433, 434,
                                         435, 436, 440, 441, 442, 443, 444, 445, 446, 450, 451, 452, 453, 454, 455, 456,
                                         500),
                        Category = c("All full-time instructional staff",
                                     "Instructional staff with faculty status",
                                     "Instructional staff, professors",
                                     "Instructional staff, associate professors",
                                     "Instructional staff, assistant professors",
                                     "Instructional staff, instructors",
                                     "Instructional staff, lecturers",
                                     "Instructional staff, no academic rank",
                                     "Tenured total",
                                     "Tenured, professors",
                                     "Tenured, associate professors",
                                     "Tenured, assistant professors",
                                     "Tenured, instructors",
                                     "Tenured, lecturers",
                                     "Tenured, no academic rank",
                                     "On-Tenure track total",
                                     "On-tenure track, professors",
                                     "On-tenure track, associate professors",
                                     "On-tenure track, assistant professors",
                                     "On-tenure track, instructors",
                                     "On-tenure track, lecturers",
                                     "On-tenure track, no academic rank",
                                     "Not on tenure track/No tenure system system total",
                                     "Not on tenure/no tenure system, professors",
                                     "Not on tenure/no tenure system, associate professors",
                                     "Not on tenure/no tenure system, assistant professors",
                                     "Not on tenure/no tenure system, instructors",
                                     "Not on tenure/no tenure system, lecturers",
                                     "Not on tenure/no tenure system, no academic rank",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, total",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, professors",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, asssociate professors",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, assistant professors",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, instructors",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts contract,lecturers",
                                     "Not on tenure track/no tenure system, multi-year and indefinite contracts, no academic rank",
                                     "Not on tenure track/no tenure system, annual contract, total",
                                     "Not on tenure track/no tenure system, annual contract, professors",
                                     "Not on tenure track/no tenure system, annual contract, asssociate professors",
                                     "Not on tenure track/no tenure system, annual contract, assistant professors",
                                     "Not on tenure track/no tenure system, annual contract, instructors",
                                     "Not on tenure track/no tenure system, annual contract,lecturers",
                                     "Not on tenure track/no tenure system, annual contract, no academic rank",
                                     "Not on tenure track/no tenure system, less-than-annual contract, total",
                                     "Not on tenure track/no tenure system, less-than-annual contract, professors",
                                     "Not on tenure track/no tenure system, less-than-annual contract, asssociate professors",
                                     "Not on tenure track/no tenure system, less-than-annual contract, assistant professors",
                                     "Not on tenure track/no tenure system, less-than-annual contract, instructors",
                                     "Not on tenure track/no tenure system, less-than-annual contract,lecturers",
                                     "Not on tenure track/no tenure system, less-than-annual contract, no academic rank",
                                     "Not on tenure track/no tenure system, multi-year contract, total",
                                     "Not on tenure track/no tenure system, multi-year contract, professors",
                                     "Not on tenure track/no tenure system, multi-year contract, associate professors",
                                     "Not on tenure track/no tenure system, multi-year contract, assistant professors",
                                     "Not on tenure track/no tenure system, multi-year contract, instructors",
                                     "Not on tenure track/no tenure system, multi-year contract, lecturers",
                                     "Not on tenure track/no tenure system, multi-year contract, no academic rank",
                                     "Not on tenure track/no tenure system, multi-year contract, total",
                                     "Not on tenure track/no tenure system, indefinite contract, professors",
                                     "Not on tenure track/no tenure system, indefinite contract, associate professors",
                                     "Not on tenure track/no tenure system, indefinite contract, assistant professors",
                                     "Not on tenure track/no tenure system, indefinite contract, instructors",
                                     "Not on tenure track/no tenure system, indefinite contract, lecturers",
                                     "Not on tenure track/no tenure system, indefinite contract, no academic rank",
                                     "Without faculty status")
                        )

usethis::use_data(staff_cat, overwrite = TRUE)
